name: plus1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  cloud_firestore: ^5.4.0
  cloud_firestore_platform_interface: ^6.4.0
  cloud_firestore_web: ^4.2.0
  cloud_functions: ^5.1.0
  cloud_functions_platform_interface: ^5.5.34
  cloud_functions_web: ^4.9.12
  collection: 1.18.0
  dropdown_button2: 2.3.9
  file_picker: ^8.0.7
  firebase_auth: ^5.2.0
  firebase_auth_platform_interface: ^7.4.4
  firebase_auth_web: ^5.12.6
  firebase_core: ^3.4.0
  firebase_core_platform_interface: ^5.2.1
  firebase_core_web: ^2.17.5
  firebase_messaging: ^15.1.0
  firebase_messaging_platform_interface: ^4.5.43
  firebase_messaging_web: ^3.8.13
  firebase_performance: ^0.10.0+5
  firebase_performance_platform_interface: ^0.1.4+41
  firebase_performance_web: ^0.1.6+13
  firebase_storage: ^12.2.0
  firebase_storage_platform_interface: ^5.1.28
  firebase_storage_web: ^3.9.13
  fl_chart: ^0.69.0
  flutter_animate: 4.5.0
  flutter_cache_manager: ^3.4.1
  flutter_card_swiper: ^7.0.1
  flutter_credit_card: 4.0.1
  flutter_google_places: 
    git:
      url: https://github.com/ShehanYjoz/flutter_google_places.git
  flutter_native_splash: ^2.4.1
  flutter_plugin_android_lifecycle: ^2.0.22
  flutter_rating_bar: 4.0.1
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  geolocator: 12.0.0
  geolocator_android: ^4.6.1
  geolocator_apple: 2.3.7
  geolocator_platform_interface: ^4.2.4
  geolocator_web: 4.0.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  google_maps: ^8.0.0
  google_maps_flutter: ^2.9.0
  google_maps_flutter_android: ^2.14.6
  google_maps_flutter_ios: ^2.13.0
  google_maps_flutter_platform_interface: ^2.9.2
  google_maps_flutter_web: ^0.5.10
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.1.30
  google_sign_in_ios: ^5.7.7
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4+2
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+13
  image_picker_for_web: ^3.0.5
  image_picker_ios: ^0.8.12
  image_picker_platform_interface: ^2.10.0
  infinite_scroll_pagination: 4.0.0
  intl: 0.19.0
  json_path: ^0.7.4
  mask_text_input_formatter: 2.9.0
  mime_type: ^1.0.1
  package_info_plus: 8.0.0
  package_info_plus_platform_interface: 3.0.0
  page_transition: 2.1.0
  path_provider: ^2.1.4
  path_provider_android: ^2.2.10
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  photo_view: ^0.15.0
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  rxdart: 0.27.7
  shared_preferences: ^2.3.2
  shared_preferences_android: ^2.3.2
  shared_preferences_foundation: ^2.5.2
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.2
  sign_in_with_apple: ^6.1.2
  sign_in_with_apple_platform_interface: ^1.1.0
  sign_in_with_apple_web: ^2.1.0
  sqflite: ^2.3.3+1
  stream_transform: 2.1.0
  table_calendar: ^3.1.2
  timeago: ^3.7.0
  tutorial_coach_mark: 1.2.11
  universal_io: 2.2.2
  url_launcher: ^6.3.0
  url_launcher_android: ^6.3.10
  url_launcher_ios: ^6.3.1
  url_launcher_platform_interface: 2.3.2
  video_player: ^2.9.1
  video_player_android: ^2.7.3
  video_player_avfoundation: 2.6.1
  video_player_platform_interface: 6.2.2
  video_player_web: ^2.3.2
  xml: 6.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.1
  package_info_plus: 8.0.0
  package_info_plus_platform_interface: 3.0.0
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: ^4.2.0
  integration_test: 
    sdk: flutter
  lints: 4.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  fonts:
    - family: 'Logo design'
      fonts:
        - asset: assets/fonts/blue.otf
          weight: 300
          style: italic

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

